services:
  sonar-golc:
    image: timothe/sonar-golc:latest # or :dev for the dev version (multi-arch: amd64 + arm64)
    container_name: sonar-golc
    ports:
      - "8092:8092"
    environment:
      GOLC_DEVOPS: Github # Github, Gitlab, BitBucket, File
    volumes:
      - /path/to/your/config:/config:ro
    restart: "unless-stopped"